      <div class="login">
        <br>
        <table>
          <thead>
          </thead>
          <tbody>
            <tr>
              <th><label>Usuario: </label></th>
              <td><input type="text" name="usuario" placeholder="Usuario"></td>
            </tr>
            <tr>
              <th><label>Contraseña: </label></th>
              <td><input type="password" name="contraseña" placeholder="Contraseña" requiered></td>
            </tr>
            <tr >
              <th colspan="2"><input type="submit" name="Ingresar"></th>
            </tr>
          </tbody>
        </table>
      </div>


<h2>Vista Index</h2>


